### ISSUE TITLE
Issue using GloBI's Taxon Graph to lookup terms by id

### ISSUE THREAD

**Issue by nleguillarme** [globalbioticinteractions/nomer#14]
Hi.

I would like to use nomer to get URIs from taxa names or ids to build a knowledge graph from tabular data. However, I am facing an issue using the globi-taxon-cache matcher (which I guess is faster than globi-enrich) with taxids. For instance, with GBIF:2436436 (Homo sapiens):

```
echo -e 'GBIF:2436436\t' | nomer append
using default matcher [globi-taxon-cache]
GBIF:2436436		NONE	GBIF:2436436	http://www.gbif.org/species/2436436
```

Same problem using the NCBI taxid. However, it works with EOL id : the id is resolved against the different taxonomies. Any advice ?

**Comment by jhpoelen** [comment]
Hi @nleguillarme thanks for open this issue! I was able to reproduce and fix this bug. I just released nomer v0.1.8 that has a fix in it. So now:

```
$ echo -e 'GBIF:2436436\t' | nomer append
using default matcher [globi-taxon-cache]
GBIF:2436436		SAME_AS	GBIF:2436436	Homo sapiens	species		Animalia | Chordata | Mammalia | Primates | Hominidae | Homo | Homo sapiens	GBIF:1 | GBIF:44 | GBIF:359 | GBIF:798 | GBIF:5483 | GBIF:2436435 | GBIF:2436436	kingdom | phylum | class | order | family | genus | species	http://eol.org/pages/327955
```

Please make sure to reinstall nomer (with version 0.1.8) and clean your term cache using ```nomer clean```.

Please comment or re-open this issue if you cannot produce.

**Comment by nleguillarme** [comment]
Thank you @jhpoelen, I see some improvements there !

I am still facing an issue with some taxids. For instance, the Achillea millefolium with taxid GBIF:9221087 is not found using globi-taxon-cache:

`GBIF:9221087		NONE	GBIF:9221087	http://www.gbif.org/species/9221087`

When using globi-enrich I obtain:

`GBIF:9221087		SAME_AS	GBIF:9221087	Achillea millefolium	species		Plantae | Tracheophyta | Magnoliopsida | Asterales | Asteraceae | Achillea | Achillea millefolium	GBIF:6 | GBIF:7707728 | GBIF:220 | GBIF:414 | GBIF:3065 | GBIF:3119995 | GBIF:9221087	kingdom | phylum | class | order | family | genus | species	http://www.gbif.org/species/9221087`

Maybe this is related to the way the GloBI's Taxon Graph is built. Does it contain all the taxa in the different taxonomies ? The taxa present in the GloBI database ?

**Comment by jhpoelen** [comment]
@nleguillarme GloBI Taxon Graph only contains taxa that are in GloBI. However, you specific example highlights some the complexities of the GBIF backbone taxonomy - GloBI has linked Achillea millefolium to https://www.gbif.org/species/3120060 (e.g., try GBIF:3120060) and GBIF backbone taxonomy also has a "doubtful" taxon id with the same name / hierarchy at https://www.gbif.org/species/9221087 .  ```globi-enrich``` uses GBIF api to retrieve the information directly. 

Just curious - how did you get to the GBIF:9221087 taxon id?

**Comment by nleguillarme** [comment]
Thank you for those clarifications. So I guess combining globi-taxon-cache for speed and globi-enrich for completeness is the way to go.

I am trying to integrate data from a csv file with a local mirror of GloBI. These data have been compiled by hand by ecologists. I'll ask them how they obtained the GBIF id for each taxon.

**Comment by jhpoelen** [comment]
Sounds like a plan. You might be interested in https://github.com/globalbioticinteractions/taxon-graph-builder . This project contains the a Make script that take unmatched GloBI names and attempt to resolve them using nomer. 

Also, note that GloBI is pretty good at taking csv files and merging it into a all of GloBI. I use "elton" a to create/find/check for mapping csv into terms that GloBI understands . For a recent example: see https://github.com/globalbioticinteractions/light2019 and template https://github.com/globalbioticinteractions/template-dataset  . Not quite sure whether it covers your use case, but I thought I'd mention it.

**Comment by nleguillarme** [comment]
Thank you for the pointers.

I don't think I completely understand what elton can be used for.
You register a new local dataset with elton update, then you can look for names and interactions in this dataset using the proper commands ?

**Comment by jhpoelen** [comment]
I currently mostly use elton for: (a) getting and caching registered datasets using ```elton update``` (b) checking whether interaction datasets can be read using ```elton check``` (c) extracting names from species interactions using ```elton names``` (d) extracting species interactions using ```elton interactions```.  

How to register a dataset is described in https://github.com/globalbioticinteractions/template-dataset#share-your-interaction-data . Or, in Spanish ; ) at https://www.globalbioticinteractions.org/es/tutorial . I'd you'd like to discuss further or have ideas, please suggest date / time to do video conference. I am in Pacific timezone.

**Comment by nleguillarme** [comment]
Ok, I will try to run elton to get a better understanding of how GloBI is built. You did an amazing work by the way.

I would be happy to discuss with you someday. I am currently working on building a biodiversity knowledge graph (mainly interactions and traits) for ecological research, and it would be great if you could give me more details about the overall GloBI project and some design choices you made :)

**Comment by nleguillarme** [comment]
Hi @jhpoelen.
Just to let you know that I released a simple python wrapper for nomer, available here : https://github.com/nleguillarme/pynomer

**Comment by jhpoelen** [comment]
@nleguillarme Cool!

I've added a reference in the nomer readme file via https://github.com/globalbioticinteractions/nomer/commit/f0a0a61d5f123f6bf4a6f0fdae9f9bf5a89ef37a . Happy to accept pull requests if you have any update / comments. 

Also, I noticed you created a docker container too . I was wondering whether we should merge this into the main project or reference it in the readme. Any ideas?

**Comment by nleguillarme** [comment]
Please feel free to merge it into the main project if you find any interest in this container.
I am a noobie for whatever concerns docker so I didn't really know what I was doing. 
I just plagiarized [this container](https://github.com/RMLio/yarrrml-rmlmapper-docker) !
